hero-z-7045-builder: build and install driver and UART app with PULP library

diff --git a/hero-z-7045-builder b/hero-z-7045-builder
--- a/hero-z-7045-builder
+++ b/hero-z-7045-builder
@@ -122,15 +122,34 @@ build_linux() {
     fi
 }
 
-build_liboffload() {
+build_offload() {
     cd ${HERO_SDK_DIR}
     update_env
 
-    cd ${HERO_SDK_DIR}/libpulp-offload
+    # Build and install the Linux kernel-level PULP driver
+    cd ${HERO_SUPPORT_DIR}/drivers/pulp
     make clean all
 
     if [ $? -ne 0 ]; then
-        echo "ERROR: build_liboffload failed, aborting now."
+        echo "ERROR: Build of the Linux PULP driver failed, aborting now."
+        exit 1
+    fi
+
+    # Build and install the PULP offload library
+    cd ${HERO_SUPPORT_DIR}/libpulp
+    make clean all
+
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Build of the PULP library failed, aborting now."
+        exit 1
+    fi
+
+    # Build and install the PULP UART reader
+    cd ${HERO_SUPPORT_DIR}/apps/uart
+    make clean all
+
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Build of the PULP UART reader failed, aborting now."
         exit 1
     fi
 }
@@ -165,7 +184,7 @@ HERO toolchain commands
     > PULP SDK
     > ARM GCC standalone toolchain
     > Linux
-    > libpulp-offload
+    > offload framework
     > HERO toolchain
 
 
@@ -177,7 +196,7 @@ Commands for building individual components
   -p : PULP SDK
   -a : ARM GCC standalone toolchain
   -l : Linux
-  -o : libpulp-offload
+  -o : offload framework
   -t : HERO toolchain
 
 EOF
@@ -191,7 +210,7 @@ do_build_riscv32_toolchain=false
 do_build_pulp_sdk=false
 do_build_arm_toolchain=false
 do_build_linux=false
-do_build_liboffload=false
+do_build_offload=false
 do_build_hero_toolchain=false
 
 while getopts hAsrpalot opt; do
@@ -203,7 +222,7 @@ while getopts hAsrpalot opt; do
             do_build_pulp_sdk=true
             do_build_arm_toolchain=true
             do_build_linux=true
-            do_build_liboffload=true
+            do_build_offload=true
             do_build_hero_toolchain=true
             ;;
         s)
@@ -222,7 +241,7 @@ while getopts hAsrpalot opt; do
             do_build_linux=true
             ;;
         o)
-            do_build_liboffload=true
+            do_build_offload=true
             ;;
         t)
             do_build_hero_toolchain=true
@@ -258,8 +277,8 @@ if [ "$do_build_linux" = true ] ; then
     build_linux
 fi
 
-if [ "$do_build_liboffload" = true ] ; then
-    build_liboffload
+if [ "$do_build_offload" = true ] ; then
+    build_offload
 fi
 
 if [ "$do_build_hero_toolchain" = true ] ; then
