hero-z-7045-env.sh: separate preparation and compilation of Linux
The generation of the ARM toolchain requires the kernel headers.

diff --git a/hero-z-7045-builder b/hero-z-7045-builder
--- a/hero-z-7045-builder
+++ b/hero-z-7045-builder
@@ -31,6 +31,21 @@ update_env() {
     source scripts/hero-z-7045-env.sh
 }
 
+prepare_linux() {
+    cd ${HERO_SDK_DIR}
+    update_env
+
+    # Does the kernel directory already exist? It may be external.
+    if [ ! -d "${HERO_LINUX_KERNEL_DIR}" ]; then
+
+        # Prepare Linux workspace and get sources
+        mkdir -p ${HERO_LINUX_WORKSPACE_DIR}
+        cp -r ${HERO_SUPPORT_DIR}/linux/zynqlinux/* ${HERO_LINUX_WORKSPACE_DIR}/.
+        cd ${HERO_LINUX_WORKSPACE_DIR}
+        ./setup.sh
+    fi
+}
+
 get_sources() {
     cd ${HERO_SDK_DIR}
     update_env
@@ -69,6 +84,9 @@ build_arm_toolchain() {
     cd ${HERO_SDK_DIR}
     update_env
 
+    # requires Linux kernel headers
+    prepare_linux
+
     cd ${HERO_TOOLCHAIN_DIR}
     ./hero_arm_toolchain_builder -dPj
 }
@@ -77,32 +95,29 @@ build_linux() {
     cd ${HERO_SDK_DIR}
     update_env
 
-    # Does the kernel directory already exist? It may be external.
-    if [ ! -d "${HERO_LINUX_KERNEL_DIR}" ]; then
+    prepare_linux
 
-        # Prepare Linux workspace and get sources
-        mkdir -p ${HERO_LINUX_WORKSPACE_DIR}
-        cp -r ${HERO_SUPPORT_DIR}/linux/zynqlinux/* ${HERO_LINUX_WORKSPACE_DIR}/.
-        cd ${HERO_LINUX_WORKSPACE_DIR}
-        ./setup.sh
+    # Try to build kernel (might fail because of missing U-Boot mkimage)
+    cd ${HERO_LINUX_KERNEL_DIR}
+    {
+        ./compile_kernel.sh  ${PARBUILD}
+    } || {
+        COMPILE_KERNEL_FAILED=1
+    }
 
-        # Try to build kernel (will fail because of missing U-Boot mkimage)
-        cd ${HERO_LINUX_KERNEL_DIR}
-        {
-            ./compile_kernel.sh  ${PARBUILD}
-        } || {
-            echo "Linux kernel build failed as expected. I will retry later."
-        }
+    if [[ ! -z "${COMPILE_KERNEL_FAILED}" ]]; then
+        echo "Linux kernel build failed as expected. I first need to build U-Boot mkimage."
 
         # Build U-Boot (needed for kernel build)
         cd ${HERO_LINUX_WORKSPACE_DIR}/u-boot-xlnx
         ./compile_loader.sh ${PARBUILD}
 
-        # Build kernel & modules
-        cd ${HERO_LINUX_KERNEL_DIR}
+        # Rebuild kernel
         ./compile_kernel.sh  ${PARBUILD}
-        ./compile_modules.sh ${PARBUILD}
     fi
+
+    # Also build modules
+    ./compile_modules.sh ${PARBUILD}
 }
 
 build_liboffload() {
